### ISSUE TITLE
os.get_terminal_size() issue with IDEs

### ISSUE THREAD

**Issue by AbnormalDistributions** [AbnormalDistributions/landsat8_scene_calculator#14]
os.get_terminal_size() does not work with certain IDEs (specifically PyCharm). Change to something that works with all IDEs.

**Comment by Atreyagaurav** [comment]
The problem with os.get_terminal_size() seems to be specific to the terminal you are using (in this case pycharm).
Can you look at these SO answers?

https://stackoverflow.com/questions/56817448/pycharm-os-get-terminal-size-not-working

https://stackoverflow.com/questions/44851652/how-to-allocate-a-pseudo-tty-in-which-to-run-scripts-from-ide/44852103#44852103

Let me know if this fixes the error as I do not have any IDE on my laptop and can't check if this problem is common to other IDEs.

**Comment by AbnormalDistributions** [comment]
added how to fix to the readme for PyCharm and IntelliJ IDEA
